# Generated by Django 4.1.3 on 2022-11-19 05:33

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('b3ack', '0002_alter_investoruser_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investoruser',
            name='watchlist',
            field=models.CharField(blank=True, default='[]', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
