# Generated by Django 4.1.3 on 2022-11-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b3ack', '0003_alter_investoruser_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('api_id', models.IntegerField()),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('abr', models.JSONField()),
                ('max', models.JSONField()),
                ('min', models.JSONField()),
                ('fch', models.JSONField()),
                ('tracked', models.BooleanField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='investoruser',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='investoruser',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to='b3ack.company'),
        ),
    ]
