# Generated by Django 4.1.3 on 2022-11-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b3ack', '0004_company_remove_investoruser_watchlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='abr',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='fch',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='max',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='min',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
