# Generated by Django 4.1.3 on 2022-11-20 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b3ack', '0005_alter_company_abr_alter_company_fch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='tracked',
        ),
    ]
