# Generated by Django 4.1.3 on 2022-11-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b3ack', '0006_remove_company_tracked'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='capture_dt',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
