# Generated by Django 4.1.3 on 2022-11-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b3ack', '0008_tracking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tracking',
            new_name='TrackTunnel',
        ),
    ]
