# Generated by Django 4.1.3 on 2022-11-21 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b3ack', '0009_rename_tracking_tracktunnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTracker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('api_id', models.IntegerField()),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('interval', models.IntegerField(blank=True, null=True)),
                ('abr', models.JSONField(blank=True, null=True)),
                ('max', models.JSONField(blank=True, null=True)),
                ('min', models.JSONField(blank=True, null=True)),
                ('fch', models.JSONField(blank=True, null=True)),
                ('capture_dt', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='tracktunnel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tracktunnel',
            name='user',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='TrackTunnel',
        ),
        migrations.AlterField(
            model_name='investoruser',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to='b3ack.companytracker'),
        ),
    ]
