# Generated by Django 4.1.3 on 2022-11-23 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b3ack', '0010_companytracker_remove_tracktunnel_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytracker',
            name='interval',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='companytracker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
