# Generated by Django 4.1.3 on 2022-11-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b3ack', '0011_alter_companytracker_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytracker',
            name='buy_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companytracker',
            name='sell_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
