# Generated by Django 4.1.3 on 2022-11-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b3ack', '0012_companytracker_buy_value_companytracker_sell_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytracker',
            name='buy_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companytracker',
            name='sell_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
