# Generated by Django 4.1.3 on 2022-11-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b3ack', '0013_alter_companytracker_buy_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytracker',
            name='buy_value',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companytracker',
            name='sell_value',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
